---

- name: Download and install logstash gpg public signing key
  apt_key:
    url:   "{{ logstash_signing_key_url }}"
    state: present

- name: Add logstash apt repository definition to apt sources list
  apt_repository:
    repo:         "{{ logstash_apt_repo }}"
    update_cache: yes
    state:        present

- name: Install logstash
  apt: 
    name:  "logstash={{ logstash_version|default('*') }}"
    state: present
