---

- name: Validate logstash config
  command: >
      "{{ logstash_bin_dir }}/logstash"
        --configtest --config "{{ logstash_conf_dir }}"

- name: Restart logstash
  service: name=logstash state=restarted
